run_task_job:
  cron: "*/15 * * * * *"
  class: "RunTaskJob"
  queue: default
update_ma5_job:
  cron: "*/1 * * * *"
  class: "UpdateMa5Job"
  queue: default
trade_history_job:
  cron: "*/5 * * * *"
  class: "TradeHistoryJob"
  queue: default
clear_trade_histroy_job:
  cron: "0 1 * * *"
  class: "ClearTradeHistroyJob"
  queue: defaul    